### ISSUE TITLE
Allow the archive step to build for the simulator

### ISSUE THREAD

**Issue by pzearfoss** [bitrise-io/steps-xcode-archive#47]
For my case, I'd like to be able to build for the simulator.  This would allow my QA team to use the build with UI automation frameworks.

**Comment by viktorbenei** [comment]
Thanks for reporting, we'll definitely find a solution for this!

**Comment by jaunesarmiento** [comment]
Hi @viktorbenei any news on this?

**Comment by viktorbenei** [comment]
@jaunesarmiento I think the usual advise is to do that with a Script step, simply calling the `xcodebuild` commands you want to, as that's quite a bit different compared to when you do an actual signed IPA - but feel free to create a feature request at https://discuss.bitrise.io/c/feature-request if you want to bump this request's priority.

The current state is: it's on our internal tracker, but not planned in the near future. We're still thinking whether this should be added/included in this step, or as a separate step, for example.

**Comment by viktorbenei** [comment]
Ohh, and of course Pull Requests are also welcome, if you'd have the time ;)

**Comment by vGubriienko** [comment]
Same feature wanted

**Comment by viktorbenei** [comment]
@vGubriienko PRs are still welcome ;)

**Comment by KumMadhu** [comment]
want to add request to have xcode for simulator. Thanks!

**Comment by godrei** [comment]
Hi, guys we started to work on this feature. It will be implemented as a new step (since this step has so many inputs and we did not want to make it more difficult to configure with new inputs for the simulator builds).
The new step's repo can be found here: https://github.com/bitrise-steplib/steps-xcode-archive-for-simulator, you can watch that repo, to get notifications about the releases.
Sorry for the inconviniences.

I'll close this issue, but if you need more info/help just create a new issue!
